trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    python -V
  displayName: 'Show Python version'

- script: |
    ${JAVA_HOME_17_X64}/bin/java -version
  displayName: 'Show Java'

- script: |
    wget -o /tmp/dita-ot.zip https://github.com/dita-ot/dita-ot/releases/download/4.1/dita-ot-4.1.zip
    unzip /tmp/dita-ot.zip
    cd /tmp/dita-ot/bin
    dita --version
  displayName: 'Download DITA-OT'