# trigger:
# - main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    python -V
  displayName: 'Show Python version'

- script: |
    pwd
    echo '---'
    git log --oneline
  displayName: 'Show git clone directory'

- script: |
    java -version
  displayName: 'Show Java'

- script: |
    gitdir=`pwd`
    wget -q -O /tmp/dita-ot.zip https://github.com/dita-ot/dita-ot/releases/download/3.7.4/dita-ot-3.7.4.zip
    cd /tmp
    unzip -q dita-ot.zip
    /tmp/dita-ot-3.7.4/bin/dita --input=${gitdir}/readme-skimmed3/DODreadme_PDF.ditamap --format=pdf --output=${gitdir}/readme-skimmed3/output
    ls -l ${gitdir}/readme-skimmed3/output
  displayName: 'Install DITA-OT and generate pdf'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: readme-skimmed3/output/DODreadme_PDF.pdf
    artifactName: DODreadme_PDF.pdf