trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    python -V
  displayName: 'Show Python version'

- script: |
    ${JAVA_HOME_17_X64}/bin/java -version
  displayName: 'Show Java'